#!/bin/bash

NAME="{{ system_user }}"                                  # Name of the application
DJANGODIR="{{ codebase_path }}"             # Django project directory
SOCKFILE=/var/run/{{ service_name }}.sock  # we will communicte using this unix socket
USER="{{ system_user }}"                                        # the user to run as
GROUP="{{ system_group }}"                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=temba.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=temba.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source {{ venv_path }}/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec {{ venv_path }}/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --daemon \
  --log-level=debug \
  --log-file="{{ log_path }}/gunicorn.log"
